---
apiVersion: v1
kind: Namespace
metadata:
  name: twitter
---
apiVersion: v1
kind: Pod
metadata:
  name: webserver
  namespace: twitter
  labels:
    app: webdb
    tier: backend
spec:
  containers:
  - name: db
    image: mysql
    ports:
      - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: jino
    volumeMounts:
      - name: mysqldb
        mountPath: /var/lib/mysql
  - name: web
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
      - name: webdata
        mountPath: /usr/share/nginx/html/
  volumes:
  - name: mysqldb
    hostPath:
      path: /var/mysql
      type: DirectoryOrCreate
  - name: webdata
    hostPath:
      path: /var/www/html
      type: DirectoryOrCreate
